# Disqus
disqus:
  shortname: murilloyonamine-github-io
# Adapte as opções abaixo conforme necessário

baseurl: ""
url: "https://murilloyonamine.github.io"
title: "Murillo Gomes Yonamine — Portfólio"
description: "Portfólio pessoal de Murillo Gomes Yonamine, estudante de Desenvolvimento de Jogos e programador de gameplay."
author_name: "Murillo"
resume_url: "/assets/files/resume.pdf"
future: true
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jemoji

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/