name: 📦 Build and deploy ASP.NET Core to GitHub Pages

env:
  DOTNET_VERSION: '9.0'  # 🧰 .NET version

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🧠 Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/v3-cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            ${{ runner.os }}-nuget-

      - name: 🔧 Restore dependencies
        run: dotnet restore

      - name: 🏗️ Build project
        run: dotnet build --configuration Release --no-restore

      - name: ✅ Run tests (optional)
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: 🚚 Publish project
        run: dotnet publish -c Release -o ./publish --no-build

      - name: ⚙️ Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: ⬆️ Upload build to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish/wwwroot

  deploy:
    name: 🚀 Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: 📤 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
