name: Static Site CI/CD

on:
  push:
    branches: [ "main", "net-integration" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js (for any JS processing)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Validate HTML files
      run: |
        echo "Validating HTML structure..."
        find . -name "*.html" -type f | head -5
        
    - name: Check for required files
      run: |
        echo "Checking project structure..."
        ls -la
        test -f index.html && echo "✓ index.html found" || echo "✗ index.html missing"
        test -d assets && echo "✓ assets directory found" || echo "✗ assets directory missing"
        test -d styles && echo "✓ styles directory found" || echo "✗ styles directory missing"
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,README.md,LICENSE'
